typedef NS_ENUM(NSInteger, NTKFaceStyle) {
	NTKFaceStyleUtilitarianNumbers = 0,
	NTKFaceStyleUtilitarianPills,
	NTKFaceStyleChronograph,
	NTKFaceStyleColorAnalog,
	NTKFaceStyleDigitalModular,
	NTKFaceStyleUserPhoto,
	NTKFaceStyleVideo,
	NTKFaceStyleTimelapse,
	NTKFaceStyleSolar,
	NTKFaceStyleAstronomy,
	NTKFaceStyleCharacter,
	NTKFaceStyleExtraLarge = 12,
	NTKFaceStyleAlbumPhoto,
	NTKFaceStyleZeusAnalog,
	NTKFaceStyleActivityAnalog = 16,
	NTKFaceStyleActivityDigital,
	NTKFaceStyleNumeralsAnalog,
	NTKFaceStyleVictoryAnalog,
	NTKFaceStyleVictoryDigital,
	NTKFaceStyleUpNext,
	NTKFaceStylePhotos,
	NTKFaceStyleKaleidoscope,
	NTKFaceStyleExplorer,
	NTKFaceStyleInfinity,
	NTKFaceStylePrideDigital,
	NTKFaceStyleAnalogBreathe,
	NTKFaceStyleAnalogSmoke,
	NTKFaceStyleWhistlerDigital,
	NTKFaceStyleWhistlerAnalog,
	NTKFaceStyleAnalogMetallic,
	NTKFaceStyleAnalogFireWater,
	NTKFaceStylePrideAnalog,
	NTKFaceStyleWhistlerSubdials,
	NTKFaceStyleOlympus,
	NTKFaceStyleSidereal,
	NTKFaceStyleBigNumeralsDigital,
	NTKFaceStyleBigNumeralsAnalog,
	NTKFaceStyleCalifornia,
	NTKFaceStyleBlackcomb,
	NTKFaceStyleSpectrumAnalog,
	NTKFaceStyleWhitetank,
};